version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Europe/Berlin"
    reviewers:
      - "bierdosenhalter"
      - "nothub"
      - "Pr3roxDLC"
      - "colesium"
      - "SooStrator1136"
      - "crxyne"
    commit-message:
      prefix: "maven"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Europe/Berlin"
    reviewers:
      - "bierdosenhalter"
      - "nothub"
      - "Pr3roxDLC"
      - "colesium"
      - "SooStrator1136"
      - "crxyne"
    commit-message:
      prefix: "github-actions"
      include: "scope"